version: '3'

services:
  commento-server:
    image: registry.gitlab.com/commento/commento
    environment:
      COMMENTO_POSTGRES: postgres://postgres:postgres@db:5432/commento?sslmode=disable
    env_file: conf.env
    depends_on:
      - db
    networks:
      - db_network
      - pub_network
  db:
    image: postgres
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - db_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

networks:
  db_network:
  pub_network:

volumes:
  postgres_data_volume:
