version: "3"
services:
  strelay:
    build: .
    env_file: conf.env
    ports:
      - "22067:22067"
      - "22070:22070"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"
    volumes:
      - strelay-keys:/strelay
volumes:
  strelay-keys:
